### ISSUE TITLE
Loading our own image dataset

### ISSUE THREAD

**Issue by aaseagrass** [AFAgarap/support-vector-machine#2]
Hello! Currently new in machine learning. I need a svm classifier in order to classify the 2 seagrass species present in our seagrass picture. Can I use this repo for that? Can I build my own dataset using this repo? Thank you! I'm a graduating undergrad ECE student that still fighting for our graduation. Hope anyone can help me.

**Comment by AFAgarap** [comment]
You may use this repository, yes. But please observe proper citation of my work. As for your dataset, you can easily do that by labelling your features (pictures), for instance, put the species picture in their respective folders.

**Comment by aaseagrass** [comment]
Thank you for allowing us to use your repo, I'll make sure to cite this properly. But I'm not familiar on how to integrate our data to your code huhuhu. Can you help us?

**Comment by AFAgarap** [comment]
Hello, @aaseagrass Kindly read this documentation on loading data: https://www.tensorflow.org/api_guides/python/reading_data.

**Comment by aaseagrass** [comment]
Thank you for that link. :) I'll study it. Thank you!

**Comment by AFAgarap** [comment]
You're welcome, happy to help. :) I'll close this issue now.
